/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export function Stage(props) {
  const { nodes, materials } = useGLTF("./map.glb");
  return (
    <group {...props} dispose={null}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube.geometry}
        material={nodes.Cube.material}
        position={[14.968, 3.705, 8.338]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane.geometry}
        material={nodes.Plane.material}
        position={[2.627, -0.093, 0.972]}
        scale={[20, 1, 20]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.rock.geometry}
        material={nodes.rock.material}
        position={[0.408, 2.55, -3.909]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.rock001.geometry}
        material={nodes.rock001.material}
        position={[-3.689, 1.491, -3.245]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.rock002.geometry}
        material={nodes.rock002.material}
        position={[-3.358, 1.735, 2.723]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Suzanne.geometry}
        material={nodes.Suzanne.material}
        position={[-0.945, 3.402, -6.757]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cylinder.geometry}
        material={nodes.Cylinder.material}
        position={[-0.81, 2.288, -7.39]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.rock003.geometry}
        material={nodes.rock003.material}
        position={[-2.453, 5.437, -3.066]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.rock004.geometry}
        material={nodes.rock004.material}
        position={[-1.786, 6.088, 5.066]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.rock005.geometry}
        material={nodes.rock005.material}
        position={[-8.989, 0.562, 7.699]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.rock006.geometry}
        material={nodes.rock006.material}
        position={[10.466, 1.377, 9.418]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.rock007.geometry}
        material={nodes.rock007.material}
        position={[-3.102, 3.23, 6.426]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.rock008.geometry}
        material={nodes.rock008.material}
        position={[6.676, 0.545, 11.188]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.rock009.geometry}
        material={nodes.rock009.material}
        position={[11.874, 0.854, 12.637]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.rock010.geometry}
        material={nodes.rock010.material}
        position={[4.457, -0.361, 14.308]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.rock011.geometry}
        material={nodes.rock011.material}
        position={[-2.495, 4.038, 11.45]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.rock012.geometry}
        material={nodes.rock012.material}
        position={[-7.342, 1.635, 11.445]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.rock013.geometry}
        material={nodes.rock013.material}
        position={[3.262, 0.217, -3.209]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.rock014.geometry}
        material={nodes.rock014.material}
        position={[2.398, 0.575, 7.845]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube001.geometry}
        material={nodes.Cube001.material}
        position={[-10.174, 2.247, 1.133]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube002.geometry}
        material={nodes.Cube002.material}
        position={[-6.176, 1.271, 3.049]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube003.geometry}
        material={nodes.Cube003.material}
        position={[4.606, 2.51, 9.116]}
      />
    </group>
  );
}

useGLTF.preload("/map.glb");